services:
  redis:
    image: redis:7.4-alpine
    container_name: log-redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    networks:
      - log-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: ./api-server
    container_name: log-api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - log-net

  consumer:
    build: ./consumer
    container_name: log-consumer
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - log-net

networks:
  log-net:

volumes:
  redis-data:
